version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
    networks:
      - menu
    depends_on:
      - database
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - menu

  database:
    image: postgres
    env_file:
      - .env/development/database
      - .env/development/web
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - menu

volumes:
  db_data:
  gem_cache:

networks:
  menu:
    driver: overlay
    attachable: true